Some more phys classes and strucure updates
setday/ultimate_py_project pull request #10
Opened 2023-02-28 17:17 UTC by smartydan

but sadly with no sence at all

2023-02-28 23:47 UTC, setday requested changes
Не забывай переводы в конце файлов(((
И исправь, пожалуйста, все комментарии

2023-02-28 23:47 UTC, setday commented on src/core/maths/Operator.h
> +    const double G = 9.81;
Лучше добавить в namespace phys в файл PhysicsDefenitions (или что-то вроде этого). Просто странно, что G в математике.

PS: g обычно в виде маленькой буквы

2023-02-28 23:47 UTC, setday commented on src/core/maths/Operator.h
> +        return y * (1.5F - 0.5F * x * y * y);
Две итерации уже много, а три - чересчур (работает тупо дольше, чем найти 1/root(x)).
Ещё третья итерация выглядит по-другому. Там не тупо повторение одного и того же. Просто так повезло, что первые две итерации одинаковы.

2023-02-28 23:47 UTC, setday commented on src/core/maths/Vector3.h
> +#include "string"
В уголках и до внутренних инклюдов:

```
#pragma once

#include <string>

#include "MathHeaders"
```

2023-02-28 23:47 UTC, setday commented on src/core/maths/Vector3.h
> +    [[nodiscard]] double len() const { return root(len2()); }
Либо и len, и len2 возвращают T, либо оба double

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/Ceil.cxx
> +#include "Ceil.h"
Ceil - это целая часть. Полагаю тут должен быть `Cell`

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/Ceil.h
> +struct Ceil {
Поч struct?

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/Particle.h
> +    ~Particle() = default;
Переводы строк между логическими блоками + конструктор и диструктор должны быть перед другими функциями

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/Particle.h
> +    double radius() const;
Get или Set? Есть два варианта: написать в названии или написать доку

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/Particle.h
> +    math::Vector3<double> _velocity, _position;
math::Vector3<double> -> vec3

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/Particle.h
> +#pragma once
Нет копирайта

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/Particle.cxx
> +//
Плохой копирайт. Не похож на наш

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/FluidContainer.h
> +#include <unordered_map>
До внутренних инклюдов:

```
#pragma once

#include <unordered_map>

#include "Ceil.h"
#include "IFluidContainer.h"
```

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/IFluidContainer.h
> +#pragma once
Копирайт + ошибка с инклюдами

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/FluidContainer.h
> + * FILE NAME : FluidContainer.h
Может **Simple**FluidContainer

2023-02-28 23:47 UTC, setday commented on src/core/physics/fluid/FluidContainer.cxx
> +         + int(particle.getZ()) * 4 * particle.radius() * particle.radius();
константы лучше выделять в локальные переменные:


```
const sizeOfCell = 2 * particle.radius();

return int(particle.getX()) + int(particle.getY()) * sizeOfCell
         + int(particle.getZ()) * sizeOfCell * sizeOfCell;
```

Кстати, кажется, что формула неверна

2023-03-01 07:52 UTC, smartydan commented on src/core/physics/fluid/Particle.h
> +    double radius() const;
get, тут все ок

2023-03-01 12:12 UTC, setday requested changes
Лучше, но есть, что исправлять. Ещё некоторые штуки остались с прошлого раза, посмотри те комменты, что не зарезолвлены.

2023-03-01 12:12 UTC, setday commented on src/core/physics/fluid/SimpleFluidContainer.cxx
> +         + int(particle.getZ()) * 4 * particleSize * particleSize;
Формула всё ещё неверна. Во-первых, так получается, что для разных партиклов разный грид , и что партиклы с позициями (100, 100, 0) и (0, 100, 100) и размерами в 1 будут в одной ячейке

2023-03-01 12:12 UTC, setday commented on src/core/physics/fluid/Particle.h
> +    double radius() const;
Так я говорю: либо `getRadius`, либо дока над функцией о том, что делает данная функция

2023-03-01 12:12 UTC, setday commented on src/core/physics/fluid/Particle.cxx
> +  _velocity.y -= dt * physics::G;
Лучше заменить на +=, а сам - внести в G

2023-03-01 12:12 UTC, setday commented on src/core/physics/fluid/Cell.h
> + * FILE NAME : Ceil.h
Ceil)

2023-03-01 12:12 UTC, setday commented on src/core/physics/fluid/Cell.h
> +// end of Ceil.h
Same

2023-03-01 12:12 UTC, setday commented on src/core/physics/fluid/Cell.cxx
> + * FILE NAME : Ceil.cxx
Same

2023-03-01 12:12 UTC, setday commented on src/core/physics/PhysicsDefs.h
> +  const double G = 9.81;
G - вектор.

2023-03-01 12:12 UTC, setday commented on src/core/maths/Operator.h
> +#pragma once
Копирайт

2023-03-01 12:17 UTC, smartydan commented on src/core/physics/fluid/SimpleFluidContainer.cxx
> +         + int(particle.getZ()) * 4 * particleSize * particleSize;
100 + 2 * 100 != 0 + 2 * 100 + 4 * 100

2023-03-01 12:17 UTC, smartydan commented on src/core/physics/fluid/SimpleFluidContainer.cxx
> +         + int(particle.getZ()) * 4 * particleSize * particleSize;
Ну а так, предложи свою

2023-03-01 12:18 UTC, smartydan commented on src/core/physics/fluid/Particle.cxx
> +  _velocity.y -= dt * physics::G;
Почему?

2023-03-01 21:07 UTC, setday commented on src/core/physics/fluid/Particle.cxx
> +  _velocity.y -= dt * physics::G;
Потому что вдруг мы решим поменыть гравитацию. И неожиданно узнаем, что она действует не по вектору, а против него.

2023-03-01 21:16 UTC, setday requested changes
Осталось 3 багули.

2023-03-01 21:16 UTC, setday commented on src/core/physics/fluid/Particle.h
> +    double radius() const;
Так и не исправлено

2023-03-01 21:16 UTC, setday commented on src/core/physics/fluid/Particle.cxx
> +  _velocity.y -= dt * physics::G;
Короче, лучше, чтобы гравитация действовала **по** вектору (т.е. по (0, -9,.8, 0 )), а не против него.

2023-03-01 21:16 UTC, setday commented on src/core/physics/fluid/SimpleFluidContainer.cxx
> +         + int(particle.getZ()) * 4 * particleSize * particleSize;
Сначало найди размеры контейнера по осям. Подели их на радиусы и найди размер ячейки.

Вычти начало отсчёта контейнера из частицы и подели полученый вектор на размеры ячеек и получишь позицию (не забудь домножить на количество ячеек в столбце и т.д.).

2023-03-02 00:08 UTC, setday approved these changes

2023-03-02 00:13 UTC, merged